/**
 * Novel overview panel — renders the story beat graph (React Flow) as the
 * primary view, with a side panel for beat details and actions.
 *
 * The graph is the authoritative story plan; beats light up as chapters are
 * written. The graph itself is generated by an AI agent — the user clicks
 * "生成故事图" to open a conversation session with a structured prompt.
 * Selecting a beat offers "推演" and "撰写" actions that also open sessions
 * with beat-specific context.
 */
import '@xyflow/react/dist/style.css';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  addEdge,
  applyEdgeChanges,
  applyNodeChanges,
  type Edge,
  type EdgeChange,
  type Node,
  type NodeChange,
  type NodeProps,
  type OnConnect,
  Handle,
  Position,
  BackgroundVariant,
} from '@xyflow/react';
import {
  BookOpen,
  Loader2,
  RefreshCw,
  Sparkles,
  PenLine,
  CircleDot,
  CheckCircle2,
  Circle,
  XCircle,
  Trash2,
  Wand2,
} from 'lucide-react';
import { useProject } from '@/contexts/ProjectContext';
import { useProjectRepos } from '@/hooks/useProjectRepos';
import { fileTreeApi, sessionsApi, storyGraphApi } from '@/lib/api';
import { getWritingPrompt } from '@/lib/writingPrompts';
import { useLayoutStore } from '@/stores/useLayoutStore';
import { useKanbanSessionContext } from '@/contexts/KanbanSessionContext';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { OverviewSessionSlot } from '@/components/panels/OverviewSessionSlot';
import type {
  StoryBeat,
  StoryGraph,
  BeatContext,
  UpdateBeatInput,
} from 'shared/types';

// ---------------------------------------------------------------------------
// Stats helpers (kept from the previous implementation)
// ---------------------------------------------------------------------------

interface OverviewStats {
  chapterCount: number;
  totalWords: number;
  characterCount: number;
  hookTotal: number;
  hookResolved: number;
  hookOpen: number;
}

const EMPTY_STATS: OverviewStats = {
  chapterCount: 0,
  totalWords: 0,
  characterCount: 0,
  hookTotal: 0,
  hookResolved: 0,
  hookOpen: 0,
};

function countWords(text: string): number {
  const cleaned = text
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^---[\s\S]*?---/m, '')
    .replace(/```[\s\S]*?```/g, '')
    .trim();
  if (!cleaned) return 0;
  const cjkMatches = cleaned.match(/[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g);
  const cjkCount = cjkMatches ? cjkMatches.length : 0;
  const latinText = cleaned
    .replace(/[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g, ' ')
    .trim();
  const latinWords = latinText ? latinText.split(/\s+/).filter(Boolean).length : 0;
  return cjkCount + latinWords;
}

async function scanWorkspace(rootPath: string): Promise<OverviewStats> {
  try {
    const chaptersDir = await fileTreeApi.listDirectoryChildren(rootPath, 'chapters');
    const chapterFiles = chaptersDir.files.filter((f) => f.endsWith('.md'));
    let totalWords = 0;
    for (const fileName of chapterFiles) {
      const filePath = `${rootPath}/chapters/${fileName}`;
      const content = await fileTreeApi.readFile(filePath);
      totalWords += countWords(content);
    }

    let characterCount = 0;
    try {
      const charsDir = await fileTreeApi.listDirectoryChildren(rootPath, '.cinyuverse/characters');
      characterCount = charsDir.files.filter((f) => f.endsWith('.md')).length;
    } catch {
      // characters dir may not exist
    }

    let hookTotal = 0;
    let hookResolved = 0;
    let hookOpen = 0;
    try {
      const hooksContent = await fileTreeApi.readFile(`${rootPath}/.cinyuverse/hooks.md`);
      const resolvedMatches = hooksContent.match(/-\s*\[[xX]\]\s/g) || [];
      const openMatches = hooksContent.match(/-\s*\[\s\]\s/g) || [];
      hookResolved = resolvedMatches.length;
      hookOpen = openMatches.length;
      hookTotal = hookResolved + hookOpen;
    } catch {
      // hooks file may not exist
    }

    return {
      chapterCount: chapterFiles.length,
      totalWords,
      characterCount,
      hookTotal,
      hookResolved,
      hookOpen,
    };
  } catch {
    return EMPTY_STATS;
  }
}

// ---------------------------------------------------------------------------
// Beat node rendering
// ---------------------------------------------------------------------------

type BeatNodeData = {
  beat: StoryBeat;
  isSelected: boolean;
};

const STATUS_STYLES: Record<
  string,
  { border: string; bg: string; icon: typeof CircleDot; label: string }
> = {
  planned: {
    border: 'border-slate-400/60',
    bg: 'bg-slate-50 dark:bg-slate-800/60',
    icon: Circle,
    label: 'text-slate-500',
  },
  current: {
    border: 'border-blue-500',
    bg: 'bg-blue-50 dark:bg-blue-950/40',
    icon: CircleDot,
    label: 'text-blue-600',
  },
  completed: {
    border: 'border-emerald-500',
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
    icon: CheckCircle2,
    label: 'text-emerald-600',
  },
  skipped: {
    border: 'border-rose-400',
    bg: 'bg-rose-50 dark:bg-rose-950/40',
    icon: XCircle,
    label: 'text-rose-500 line-through',
  },
  revised: {
    border: 'border-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-950/40',
    icon: PenLine,
    label: 'text-amber-600',
  },
};

const BEAT_TYPE_LABELS: Record<string, string> = {
  plot_point: '情节点',
  character_arc: '角色弧',
  hook_plant: '埋伏笔',
  hook_advance: '推进伏笔',
  hook_resolve: '回收伏笔',
  world_change: '世界变化',
  relationship_shift: '关系转变',
  climax: '高潮',
  turning_point: '转折点',
};

function BeatNodeComponent({ data }: NodeProps) {
  const nodeData = data as unknown as BeatNodeData;
  const { beat, isSelected } = nodeData;
  const style = STATUS_STYLES[beat.status] ?? STATUS_STYLES.planned;
  const Icon = style.icon;
  return (
    <div
      className={cn(
        'rounded-lg border-2 px-3 py-2 min-w-[160px] max-w-[220px] shadow-sm transition-shadow',
        style.border,
        style.bg,
        isSelected && 'ring-2 ring-offset-1 ring-blue-400 shadow-md'
      )}
    >
      <Handle type="target" position={Position.Top} className="!bg-slate-400" />
      <div className="flex items-center gap-1.5 mb-1">
        <Icon className={cn('h-3.5 w-3.5', style.label)} />
        <span className="text-[10px] uppercase tracking-wide text-slate-400">
          {BEAT_TYPE_LABELS[beat.beat_type] ?? beat.beat_type}
        </span>
      </div>
      <div className="text-sm font-medium text-foreground leading-snug line-clamp-2">
        {beat.title}
      </div>
      {beat.chapter_hint != null && (
        <div className="text-[10px] text-slate-400 mt-1">第 {Number(beat.chapter_hint)} 章</div>
      )}
      <Handle type="source" position={Position.Bottom} className="!bg-slate-400" />
    </div>
  );
}

const nodeTypes = { beatNode: BeatNodeComponent };

// ---------------------------------------------------------------------------
// Edge styling
// ---------------------------------------------------------------------------

const EDGE_STYLES: Record<string, { stroke: string; dashed: boolean; label: string }> = {
  sequential: { stroke: '#94a3b8', dashed: false, label: '顺序' },
  causal: { stroke: '#f97316', dashed: false, label: '因果' },
  foreshadow: { stroke: '#ef4444', dashed: true, label: '伏笔' },
  parallel: { stroke: '#3b82f6', dashed: false, label: '并行' },
  alternative: { stroke: '#a855f7', dashed: true, label: '备选' },
  character_arc: { stroke: '#a855f7', dashed: true, label: '角色弧' },
  item_flow: { stroke: '#14b8a6', dashed: false, label: '物品流' },
};

// ---------------------------------------------------------------------------
// Layout — simple layered DAG layout by sort_order + volume
// ---------------------------------------------------------------------------

function layoutGraph(beats: StoryBeat[]): Map<string, { x: number; y: number }> {
  const positions = new Map<string, { x: number; y: number }>();
  if (beats.length === 0) return positions;

  const sorted = [...beats].sort((a, b) => {
    const va = Number(a.volume ?? 0);
    const vb = Number(b.volume ?? 0);
    if (va !== vb) return va - vb;
    return Number(a.sort_order) - Number(b.sort_order);
  });

  const NODE_W = 220;
  const NODE_H = 90;
  const GAP_X = 60;
  const GAP_Y = 80;
  const MAX_PER_ROW = 4;

  sorted.forEach((beat, idx) => {
    const row = Math.floor(idx / MAX_PER_ROW);
    const col = idx % MAX_PER_ROW;
    positions.set(beat.id, {
      x: col * (NODE_W + GAP_X),
      y: row * (NODE_H + GAP_Y),
    });
  });
  return positions;
}

// ---------------------------------------------------------------------------
// Main panel
// ---------------------------------------------------------------------------

export function NovelOverviewPanel() {
  const { t } = useTranslation(['panels', 'writingPrompts']);
  const { projectId } = useProject();
  const { data: repos } = useProjectRepos(projectId);
  const rootPath = repos?.[0]?.path ?? '';

  const [stats, setStats] = useState<OverviewStats>(EMPTY_STATS);
  const [graph, setGraph] = useState<StoryGraph | null>(null);
  const [graphLoading, setGraphLoading] = useState(false);
  const [graphError, setGraphError] = useState<string | null>(null);
  const [actionLoading, setActionLoading] = useState(false);

  const [selectedBeatId, setSelectedBeatId] = useState<string | null>(null);
  const [beatContext, setBeatContext] = useState<BeatContext | null>(null);
  const [contextLoading, setContextLoading] = useState(false);

  const [statusFilter, setStatusFilter] = useState<string>('all');

  // ----- refresh stats -----
  const refreshStats = useCallback(async () => {
    if (!rootPath) {
      setStats(EMPTY_STATS);
      return;
    }
    try {
      const result = await scanWorkspace(rootPath);
      setStats(result);
    } catch {
      setStats(EMPTY_STATS);
    }
  }, [rootPath]);

  // ----- refresh graph -----
  const refreshGraph = useCallback(async () => {
    if (!projectId) {
      setGraph(null);
      return;
    }
    setGraphLoading(true);
    setGraphError(null);
    try {
      const result = await storyGraphApi.getGraph(projectId);
      setGraph(result);
    } catch (err) {
      setGraphError(err instanceof Error ? err.message : String(err));
      setGraph(null);
    } finally {
      setGraphLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    refreshStats();
    refreshGraph();
  }, [refreshStats, refreshGraph]);

  // ----- build context when selection changes -----
  useEffect(() => {
    if (!selectedBeatId) {
      setBeatContext(null);
      return;
    }
    setContextLoading(true);
    let cancelled = false;
    storyGraphApi
      .buildBeatContext(selectedBeatId)
      .then((ctx: BeatContext) => {
        if (!cancelled) setBeatContext(ctx);
      })
      .catch(() => {
        if (!cancelled) setBeatContext(null);
      })
      .finally(() => {
        if (!cancelled) setContextLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [selectedBeatId]);

  // ----- React Flow nodes/edges -----
  const positions = useMemo(
    () => (graph ? layoutGraph(graph.beats) : new Map<string, { x: number; y: number }>()),
    [graph]
  );

  const nodes = useMemo<Node[]>(() => {
    if (!graph) return [];
    return graph.beats
      .filter((b) => statusFilter === 'all' || b.status === statusFilter)
      .map((beat) => ({
        id: beat.id,
        type: 'beatNode',
        position: positions.get(beat.id) ?? { x: 0, y: 0 },
        data: { beat, isSelected: beat.id === selectedBeatId } as unknown as Record<string, unknown>,
        selected: beat.id === selectedBeatId,
      }));
  }, [graph, positions, selectedBeatId, statusFilter]);

  const edges = useMemo<Edge[]>(() => {
    if (!graph) return [];
    const visibleIds = new Set(
      graph.beats
        .filter((b) => statusFilter === 'all' || b.status === statusFilter)
        .map((b) => b.id)
    );
    return graph.edges
      .filter((e) => visibleIds.has(e.from_beat) && visibleIds.has(e.to_beat))
      .map((edge) => {
        const style = EDGE_STYLES[edge.edge_type] ?? EDGE_STYLES.sequential;
        return {
          id: `${edge.from_beat}->${edge.to_beat}:${edge.edge_type}`,
          source: edge.from_beat,
          target: edge.to_beat,
          label: style.label,
          type: 'smoothstep',
          style: {
            stroke: style.stroke,
            strokeDasharray: style.dashed ? '6 4' : undefined,
          },
        };
      });
  }, [graph, statusFilter]);

  const [rfNodes, setRfNodes] = useState<Node[]>(nodes);
  const [rfEdges, setRfEdges] = useState<Edge[]>(edges);

  useEffect(() => setRfNodes(nodes), [nodes]);
  useEffect(() => setRfEdges(edges), [edges]);

  const onNodesChange = useCallback(
    (changes: NodeChange[]) => setRfNodes((nds) => applyNodeChanges(changes, nds)),
    []
  );
  const onEdgesChange = useCallback(
    (changes: EdgeChange[]) => setRfEdges((eds) => applyEdgeChanges(changes, eds)),
    []
  );
  const onConnect: OnConnect = useCallback(
    (connection) => {
      const fromBeat = connection.source;
      const toBeat = connection.target;
      if (projectId && fromBeat && toBeat) {
        storyGraphApi
          .createEdge({ from_beat: fromBeat, to_beat: toBeat, edge_type: 'sequential', note: null })
          .then(() => refreshGraph())
          .catch(() => undefined);
      }
      setRfEdges((eds) =>
        addEdge({ ...connection, type: 'smoothstep' }, eds)
      );
    },
    [projectId, refreshGraph]
  );

  const onNodeClick = useCallback((_: unknown, node: Node) => {
    setSelectedBeatId(node.id);
  }, []);

  const selectedBeat = useMemo(
    () => graph?.beats.find((b) => b.id === selectedBeatId) ?? null,
    [graph, selectedBeatId]
  );

  // ----- agent session actions -----
  const { replaceRightSession } = useKanbanSessionContext();
  const setRightPanelVisible = useLayoutStore(
    (state) => state.setRightPanelVisible
  );

  const openAgentSession = useCallback(
    async (promptText: string, sessionName: string) => {
      if (!projectId) return;
      setActionLoading(true);
      try {
        // Ensure a workspace exists for this project
        let workspaceId: string | null = null;
        try {
          const workspace = await sessionsApi.ensureProjectWorkspace({
            project_id: projectId,
            branch: null,
          });
          workspaceId = workspace.id;
        } catch {
          // fallback: try to find existing workspace from repos
        }

        const session = await sessionsApi.createProject({
          project_id: projectId,
          workspace_id: workspaceId,
          name: sessionName,
          initial_prompt: promptText,
        });

        // Show the right panel with the new session — no navigation,
        // the conversation renders inline in the overview's session slot.
        if (workspaceId) {
          replaceRightSession({
            sessionId: session.id,
            workspaceId,
          });
          setRightPanelVisible(true);
        }
      } catch (err) {
        setGraphError(err instanceof Error ? err.message : String(err));
      } finally {
        setActionLoading(false);
      }
    },
    [projectId, replaceRightSession, setRightPanelVisible]
  );

  const handleGenerateGraph = useCallback(() => {
    const tpl = getWritingPrompt('generate-story-graph');
    if (!tpl) return;
    const prompt = tpl.build({
      bookName: undefined,
      guidance: '',
    });
    void openAgentSession(prompt, t('panels:overview.generateStoryGraph'));
  }, [openAgentSession, t]);

  const handleInferBeat = useCallback(() => {
    if (!selectedBeat || !beatContext) return;
    const tpl = getWritingPrompt('infer-beat');
    if (!tpl) return;
    const prompt = tpl.build({
      beatId: selectedBeat.id,
      beatTitle: selectedBeat.title,
      beatDescription: selectedBeat.description ?? '',
      beatContext: JSON.stringify(
        {
          beat: {
            id: beatContext.beat.id,
            title: beatContext.beat.title,
            description: beatContext.beat.description,
            beat_type: beatContext.beat.beat_type,
            status: beatContext.beat.status,
            chapter_hint: beatContext.beat.chapter_hint,
          },
          predecessors: beatContext.predecessors.map((p) => ({
            id: p.id,
            title: p.title,
            status: p.status,
          })),
          successors: beatContext.successors.map((s) => ({
            id: s.id,
            title: s.title,
            status: s.status,
          })),
          characters: beatContext.characters,
          related_hooks: beatContext.related_hooks,
        },
        null,
        2
      ),
    });
    void openAgentSession(prompt, `${t('panels:overview.inferBeat')}: ${selectedBeat.title}`);
  }, [selectedBeat, beatContext, openAgentSession, t]);

  const handleWriteBeat = useCallback(() => {
    if (!selectedBeat || !beatContext) return;
    const tpl = getWritingPrompt('write-beat');
    if (!tpl) return;
    const chapterNum = selectedBeat.chapter_hint
      ? Number(selectedBeat.chapter_hint)
      : undefined;
    const prompt = tpl.build({
      beatId: selectedBeat.id,
      beatTitle: selectedBeat.title,
      beatDescription: selectedBeat.description ?? '',
      chapterNumber: chapterNum,
      beatContext: JSON.stringify(
        {
          beat: {
            id: beatContext.beat.id,
            title: beatContext.beat.title,
            description: beatContext.beat.description,
            beat_type: beatContext.beat.beat_type,
            status: beatContext.beat.status,
            chapter_hint: beatContext.beat.chapter_hint,
            completion_criteria: beatContext.beat.completion_criteria,
          },
          predecessors: beatContext.predecessors.map((p) => ({
            id: p.id,
            title: p.title,
            status: p.status,
            completed_chapter: p.completed_chapter,
          })),
          successors: beatContext.successors.map((s) => ({
            id: s.id,
            title: s.title,
            status: s.status,
          })),
          characters: beatContext.characters,
          related_hooks: beatContext.related_hooks,
        },
        null,
        2
      ),
    });
    void openAgentSession(prompt, `${t('panels:overview.writeBeat')}: ${selectedBeat.title}`);
  }, [selectedBeat, beatContext, openAgentSession, t]);

  // ----- status update (quick actions, no form) -----
  const updateStatus = useCallback(
    async (beatId: string, status: string) => {
      try {
        const payload: UpdateBeatInput = {
          status,
          title: null,
          description: null,
          beat_type: null,
          chapter_hint: null,
          completed_chapter: null,
          characters: null,
          hooks: null,
          volume: null,
          arc: null,
          sort_order: null,
          completion_criteria: null,
        };
        await storyGraphApi.updateBeat(beatId, payload);
        await refreshGraph();
      } catch (err) {
        setGraphError(err instanceof Error ? err.message : String(err));
      }
    },
    [refreshGraph]
  );

  const deleteBeat = useCallback(
    async (beatId: string) => {
      if (!confirm(t('panels:overview.deleteConfirm'))) return;
      try {
        await storyGraphApi.deleteBeat(beatId);
        if (selectedBeatId === beatId) setSelectedBeatId(null);
        await refreshGraph();
      } catch (err) {
        setGraphError(err instanceof Error ? err.message : String(err));
      }
    },
    [selectedBeatId, refreshGraph, t]
  );

  // ----- derived stats -----
  const beatStats = useMemo(() => {
    if (!graph) return { total: 0, completed: 0, current: 0, planned: 0 };
    const total = graph.beats.length;
    const completed = graph.beats.filter((b) => b.status === 'completed').length;
    const current = graph.beats.filter((b) => b.status === 'current').length;
    const planned = graph.beats.filter((b) => b.status === 'planned').length;
    return { total, completed, current, planned };
  }, [graph]);

  // ----- render -----
  if (!projectId) {
    return (
      <div className="overview-overlay bg-background text-foreground flex h-full w-full items-center justify-center">
        <p className="text-muted-foreground">{t('panels:overview.noProject')}</p>
      </div>
    );
  }

  return (
    <div className="overview-overlay bg-background text-foreground flex h-full w-full flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b px-4 py-2">
        <div className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold">{t('panels:overview.storyGraph')}</h2>
          <span className="text-xs text-muted-foreground">
            {t('panels:overview.statsBeats', beatStats)}
          </span>
        </div>
        <div className="flex items-center gap-1.5">
          <Button size="sm" variant="secondary" onClick={handleGenerateGraph} disabled={actionLoading}>
            <Wand2 className="h-3.5 w-3.5" />
            {t('panels:overview.generateStoryGraph')}
          </Button>
          <Button size="sm" variant="ghost" onClick={() => { refreshGraph(); refreshStats(); }}>
            <RefreshCw className={cn('h-3.5 w-3.5', graphLoading && 'animate-spin')} />
          </Button>
        </div>
      </div>

      {/* Stats strip */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 border-b px-4 py-1.5 text-xs text-muted-foreground">
        <span>{t('panels:overview.chapterCount')}: {stats.chapterCount}</span>
        <span>{t('panels:overview.totalWords')}: {stats.totalWords.toLocaleString()}</span>
        <span>{t('panels:overview.characterCount')}: {stats.characterCount}</span>
        <span>
          {t('panels:overview.hooks')}: {stats.hookTotal}
          {stats.hookTotal > 0 && (
            <span className="ml-1">
              ({t('panels:overview.hookResolution', {
                resolved: stats.hookResolved,
                open: stats.hookOpen,
                rate: stats.hookTotal > 0 ? Math.round((stats.hookResolved / stats.hookTotal) * 100) : 0,
              })})
            </span>
          )}
        </span>
      </div>

      {/* Filter bar */}
      <div className="flex items-center gap-1.5 border-b px-4 py-1.5">
        {['all', 'planned', 'current', 'completed', 'skipped'].map((s) => (
          <Button
            key={s}
            size="sm"
            variant={statusFilter === s ? 'secondary' : 'ghost'}
            onClick={() => setStatusFilter(s)}
            className="h-6 px-2 text-xs"
          >
            {t(`panels:overview.filter${s.charAt(0).toUpperCase() + s.slice(1)}`)}
          </Button>
        ))}
      </div>

      {/* Main content: graph + side panel */}
      <div className="flex flex-1 overflow-hidden">
        <div className="relative flex-1">
          {graphLoading && (
            <div className="absolute inset-0 z-10 flex items-center justify-center bg-background/60">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              <span className="ml-2 text-sm text-muted-foreground">
                {t('panels:overview.graphLoading')}
              </span>
            </div>
          )}
          {graphError && (
            <div className="absolute inset-0 z-10 flex items-center justify-center">
              <p className="text-sm text-rose-500">{t('panels:overview.graphError')}: {graphError}</p>
            </div>
          )}
          {!graphLoading && graph && graph.beats.length === 0 && (
            <div className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3">
              <p className="text-sm text-muted-foreground">{t('panels:overview.graphEmpty')}</p>
              <Button size="sm" variant="secondary" onClick={handleGenerateGraph} disabled={actionLoading}>
                <Wand2 className="h-3.5 w-3.5" />
                {t('panels:overview.generateStoryGraph')}
              </Button>
            </div>
          )}
          {actionLoading && (
            <div className="absolute inset-0 z-20 flex items-center justify-center bg-background/60">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              <span className="ml-2 text-sm text-muted-foreground">
                {t('panels:overview.openingSession')}
              </span>
            </div>
          )}
          {graph && graph.beats.length > 0 && (
            <ReactFlow
              nodes={rfNodes}
              edges={rfEdges}
              nodeTypes={nodeTypes}
              onNodesChange={onNodesChange}
              onEdgesChange={onEdgesChange}
              onConnect={onConnect}
              onNodeClick={onNodeClick}
              fitView
              fitViewOptions={{ padding: 0.2 }}
              proOptions={{ hideAttribution: true }}
            >
              <Background variant={BackgroundVariant.Dots} gap={20} size={1} />
              <Controls showInteractive={false} />
              <MiniMap
                pannable
                zoomable
                nodeColor={(n) => {
                  const beat = (n.data as unknown as BeatNodeData)?.beat;
                  if (!beat) return '#94a3b8';
                  switch (beat.status) {
                    case 'completed': return '#10b981';
                    case 'current': return '#3b82f6';
                    case 'skipped': return '#f43f5e';
                    case 'revised': return '#f59e0b';
                    default: return '#94a3b8';
                  }
                }}
              />
            </ReactFlow>
          )}
        </div>

        {/* Side panel: beat details + agent actions */}
        {selectedBeat && (
          <div className="w-72 border-l overflow-y-auto p-3 space-y-3">
            <div>
              <div className="text-[10px] uppercase tracking-wide text-muted-foreground">
                {BEAT_TYPE_LABELS[selectedBeat.beat_type] ?? selectedBeat.beat_type}
              </div>
              <h3 className="text-sm font-semibold leading-snug">{selectedBeat.title}</h3>
              <div className="mt-1 text-xs text-muted-foreground">
                {t('panels:overview.beatStatus')}: {selectedBeat.status}
              </div>
            </div>

            {selectedBeat.description && (
              <p className="text-xs text-muted-foreground leading-relaxed">
                {selectedBeat.description}
              </p>
            )}

            {selectedBeat.chapter_hint != null && (
              <div className="text-xs">
                <span className="text-muted-foreground">{t('panels:overview.beatChapter')}: </span>
                <span>第 {Number(selectedBeat.chapter_hint)} 章</span>
              </div>
            )}

            {contextLoading ? (
              <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
                <Loader2 className="h-3 w-3 animate-spin" /> {t('panels:overview.graphLoading')}
              </div>
            ) : beatContext ? (
              <div className="space-y-2 text-xs">
                {beatContext.predecessors.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatPredecessors')}
                    </div>
                    <ul className="list-disc pl-4 space-y-0.5">
                      {beatContext.predecessors.map((p) => (
                        <li key={p.id} className="cursor-pointer hover:text-blue-500"
                          onClick={() => setSelectedBeatId(p.id)}>
                          {p.title}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {beatContext.successors.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatSuccessors')}
                    </div>
                    <ul className="list-disc pl-4 space-y-0.5">
                      {beatContext.successors.map((s) => (
                        <li key={s.id} className="cursor-pointer hover:text-blue-500"
                          onClick={() => setSelectedBeatId(s.id)}>
                          {s.title}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {beatContext.characters.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatCharacters')}
                    </div>
                    <div className="flex flex-wrap gap-1">
                      {beatContext.characters.map((c) => (
                        <span key={c} className="rounded bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5">
                          {c}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {beatContext.related_hooks.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatHooks')}
                    </div>
                    <div className="flex flex-wrap gap-1">
                      {beatContext.related_hooks.map((h) => (
                        <span key={h} className="rounded bg-rose-50 dark:bg-rose-950/40 px-1.5 py-0.5 text-rose-600">
                          {h}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : null}

            {/* Agent actions — primary */}
            <div className="flex flex-col gap-1.5 pt-2 border-t">
              <Button size="sm" variant="secondary" onClick={handleInferBeat} disabled={actionLoading || !beatContext}>
                <Sparkles className="h-3.5 w-3.5" /> {t('panels:overview.inferBeat')}
              </Button>
              <Button size="sm" variant="secondary" onClick={handleWriteBeat} disabled={actionLoading || !beatContext}>
                <PenLine className="h-3.5 w-3.5" /> {t('panels:overview.writeBeat')}
              </Button>
            </div>

            {/* Quick status actions */}
            <div className="flex flex-col gap-1.5 pt-2 border-t">
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'current')}>
                <CircleDot className="h-3.5 w-3.5" /> {t('panels:overview.markCurrent')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'completed')}>
                <CheckCircle2 className="h-3.5 w-3.5" /> {t('panels:overview.markCompleted')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'planned')}>
                <Circle className="h-3.5 w-3.5" /> {t('panels:overview.markPlanned')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => deleteBeat(selectedBeat.id)}>
                <Trash2 className="h-3.5 w-3.5" /> {t('panels:overview.deleteBeat')}
              </Button>
            </div>
          </div>
        )}

        {/* Inline conversation session slot — adopts the shared right panel host */}
        <OverviewSessionSlot visible={true} />
      </div>
    </div>
  );
}
