/**
 * Novel overview panel — renders the story beat graph (React Flow) as the
 * primary view, with a side panel for beat details and actions.
 *
 * The graph is the authoritative story plan; beats light up as chapters are
 * written. The graph itself is generated by an AI agent — the user clicks
 * "生成故事图" to open a conversation session with a structured prompt.
 * Selecting a beat offers "推演" and "撰写" actions that also open sessions
 * with beat-specific context.
 */
import '@xyflow/react/dist/style.css';

import dagre from 'dagre';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  addEdge,
  applyEdgeChanges,
  applyNodeChanges,
  type Edge,
  type EdgeChange,
  type Node,
  type NodeChange,
  type NodeProps,
  type OnConnect,
  Handle,
  Position,
  BackgroundVariant,
} from '@xyflow/react';
import {
  BookOpen,
  Loader2,
  RefreshCw,
  Sparkles,
  PenLine,
  CircleDot,
  CheckCircle2,
  Circle,
  XCircle,
  Trash2,
  Wand2,
  ChevronDown,
  ChevronRight,
  Layers,
  Maximize2,
  Minimize2,
} from 'lucide-react';
import { useProject } from '@/contexts/ProjectContext';
import { useProjectRepos } from '@/hooks/useProjectRepos';
import { fileTreeApi } from '@/lib/api';
import { getWritingPrompt } from '@/lib/writingPrompts';
import { useLayoutStore } from '@/stores/useLayoutStore';
import { useComposerPrefillStore } from '@/stores/useComposerPrefillStore';
import { useKanbanSessionContext } from '@/contexts/KanbanSessionContext';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { OverviewSessionSlot } from '@/components/panels/OverviewSessionSlot';
// The JSON file format uses arrays for characters/hooks, while the SQLite
// model uses JSON strings. We use a local type that matches the file format.
type JsonBeat = {
  id: string;
  title: string;
  description?: string | null;
  beat_type: string;
  chapter_hint?: number | null;
  status: string;
  characters?: string[] | null;
  hooks?: string[] | null;
  volume?: number | null;
  arc?: string | null;
  sort_order?: number;
  completion_criteria?: string[] | null;
};

type JsonGraph = {
  beats: JsonBeat[];
  edges: Array<{ from_beat: string; to_beat: string; edge_type: string; note?: string | null }>;
};

type JsonBeatContext = {
  beat: JsonBeat;
  predecessors: JsonBeat[];
  successors: JsonBeat[];
  characters: string[];
  related_hooks: string[];
};

// ---------------------------------------------------------------------------
// Stats helpers (kept from the previous implementation)
// ---------------------------------------------------------------------------

interface OverviewStats {
  chapterCount: number;
  totalWords: number;
  characterCount: number;
  hookTotal: number;
  hookResolved: number;
  hookOpen: number;
}

const EMPTY_STATS: OverviewStats = {
  chapterCount: 0,
  totalWords: 0,
  characterCount: 0,
  hookTotal: 0,
  hookResolved: 0,
  hookOpen: 0,
};

function countWords(text: string): number {
  const cleaned = text
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/^---[\s\S]*?---/m, '')
    .replace(/```[\s\S]*?```/g, '')
    .trim();
  if (!cleaned) return 0;
  const cjkMatches = cleaned.match(/[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g);
  const cjkCount = cjkMatches ? cjkMatches.length : 0;
  const latinText = cleaned
    .replace(/[\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff]/g, ' ')
    .trim();
  const latinWords = latinText ? latinText.split(/\s+/).filter(Boolean).length : 0;
  return cjkCount + latinWords;
}

async function scanWorkspace(rootPath: string): Promise<OverviewStats> {
  try {
    const chaptersDir = await fileTreeApi.listDirectoryChildren(rootPath, 'chapters');
    const chapterFiles = chaptersDir.files.filter((f) => f.endsWith('.md'));
    let totalWords = 0;
    for (const fileName of chapterFiles) {
      const filePath = `${rootPath}/chapters/${fileName}`;
      const content = await fileTreeApi.readFile(filePath);
      totalWords += countWords(content);
    }

    let characterCount = 0;
    try {
      const charsDir = await fileTreeApi.listDirectoryChildren(rootPath, '.cinyuverse/characters');
      characterCount = charsDir.files.filter((f) => f.endsWith('.md')).length;
    } catch {
      // characters dir may not exist
    }

    let hookTotal = 0;
    let hookResolved = 0;
    let hookOpen = 0;
    try {
      const hooksContent = await fileTreeApi.readFile(`${rootPath}/.cinyuverse/hooks.md`);
      const resolvedMatches = hooksContent.match(/-\s*\[[xX]\]\s/g) || [];
      const openMatches = hooksContent.match(/-\s*\[\s\]\s/g) || [];
      hookResolved = resolvedMatches.length;
      hookOpen = openMatches.length;
      hookTotal = hookResolved + hookOpen;
    } catch {
      // hooks file may not exist
    }

    return {
      chapterCount: chapterFiles.length,
      totalWords,
      characterCount,
      hookTotal,
      hookResolved,
      hookOpen,
    };
  } catch {
    return EMPTY_STATS;
  }
}

// ---------------------------------------------------------------------------
// Beat node rendering
// ---------------------------------------------------------------------------

type BeatNodeData = {
  beat: JsonBeat;
  isSelected: boolean;
};

const STATUS_STYLES: Record<
  string,
  { border: string; bg: string; icon: typeof CircleDot; label: string }
> = {
  planned: {
    border: 'border-slate-400/60',
    bg: 'bg-slate-50 dark:bg-slate-800/60',
    icon: Circle,
    label: 'text-slate-500',
  },
  current: {
    border: 'border-blue-500',
    bg: 'bg-blue-50 dark:bg-blue-950/40',
    icon: CircleDot,
    label: 'text-blue-600',
  },
  completed: {
    border: 'border-emerald-500',
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
    icon: CheckCircle2,
    label: 'text-emerald-600',
  },
  skipped: {
    border: 'border-rose-400',
    bg: 'bg-rose-50 dark:bg-rose-950/40',
    icon: XCircle,
    label: 'text-rose-500 line-through',
  },
  revised: {
    border: 'border-amber-500',
    bg: 'bg-amber-50 dark:bg-amber-950/40',
    icon: PenLine,
    label: 'text-amber-600',
  },
};

const BEAT_TYPE_LABELS: Record<string, string> = {
  plot_point: '情节点',
  character_arc: '角色弧',
  hook_plant: '埋伏笔',
  hook_advance: '推进伏笔',
  hook_resolve: '回收伏笔',
  world_change: '世界变化',
  relationship_shift: '关系转变',
  climax: '高潮',
  turning_point: '转折点',
};

// Top accent bar color per beat type — gives each node a visual identity
const BEAT_TYPE_ACCENT: Record<string, string> = {
  plot_point: '#6366f1',
  character_arc: '#8b5cf6',
  hook_plant: '#ef4444',
  hook_advance: '#f97316',
  hook_resolve: '#22c55e',
  world_change: '#06b6d4',
  relationship_shift: '#ec4899',
  climax: '#eab308',
  turning_point: '#f43f5e',
};

function BeatNodeComponent({ data }: NodeProps) {
  const nodeData = data as unknown as BeatNodeData;
  const { beat, isSelected } = nodeData;
  const style = STATUS_STYLES[beat.status] ?? STATUS_STYLES.planned;
  const Icon = style.icon;
  const accent = BEAT_TYPE_ACCENT[beat.beat_type] ?? '#94a3b8';
  return (
    <div
      className={cn(
        'rounded-lg border-2 shadow-sm transition-all overflow-hidden',
        'min-w-[180px] max-w-[220px]',
        style.border,
        style.bg,
        isSelected && 'ring-2 ring-offset-1 ring-blue-400 shadow-lg scale-[1.02]'
      )}
    >
      <Handle type="target" position={Position.Top} className="!bg-slate-400 !w-2 !h-2" />
      {/* Accent bar */}
      <div className="h-1 w-full" style={{ backgroundColor: accent }} />
      <div className="px-3 py-2">
        <div className="flex items-center gap-1.5 mb-1">
          <Icon className={cn('h-3.5 w-3.5 shrink-0', style.label)} />
          <span
            className="text-[10px] font-semibold uppercase tracking-wide"
            style={{ color: accent }}
          >
            {BEAT_TYPE_LABELS[beat.beat_type] ?? beat.beat_type}
          </span>
          {beat.status === 'current' && (
            <span className="ml-auto text-[9px] rounded-full bg-blue-500 text-white px-1.5 py-0.5 animate-pulse">
              当前
            </span>
          )}
        </div>
        <div className="text-sm font-medium text-foreground leading-snug line-clamp-2">
          {beat.title}
        </div>
        {beat.chapter_hint != null && (
          <div className="text-[10px] text-slate-400 mt-1 flex items-center gap-1">
            <span className="inline-block w-1 h-1 rounded-full bg-slate-400" />
            第 {Number(beat.chapter_hint)} 章
          </div>
        )}
        {beat.characters && beat.characters.length > 0 && (
          <div className="flex flex-wrap gap-0.5 mt-1">
            {beat.characters.slice(0, 3).map((c) => (
              <span
                key={c}
                className="text-[9px] rounded bg-slate-200/60 dark:bg-slate-700/60 px-1 py-0.5 text-slate-600 dark:text-slate-300"
              >
                {c}
              </span>
            ))}
            {beat.characters.length > 3 && (
              <span className="text-[9px] text-slate-400">+{beat.characters.length - 3}</span>
            )}
          </div>
        )}
      </div>
      <Handle type="source" position={Position.Bottom} className="!bg-slate-400 !w-2 !h-2" />
    </div>
  );
}

const nodeTypes = { beatNode: BeatNodeComponent, arcNode: ArcNodeComponent };

// ---------------------------------------------------------------------------
// Progressive Disclosure: Arc-level macro node
// ---------------------------------------------------------------------------

type ArcNodeData = {
  arc: string;
  beatCount: number;
  statusCounts: Record<string, number>;
  characters: string[];
  isExpanded: boolean;
  onToggle: (arc: string) => void;
};

function ArcNodeComponent({ data }: NodeProps) {
  const nodeData = data as unknown as ArcNodeData;
  const { arc, beatCount, statusCounts, characters, isExpanded, onToggle } = nodeData;
  const completed = statusCounts.completed ?? 0;
  const current = statusCounts.current ?? 0;
  const planned = statusCounts.planned ?? 0;
  const skipped = statusCounts.skipped ?? 0;
  const progress = beatCount > 0 ? Math.round((completed / beatCount) * 100) : 0;

  return (
    <div
      className={cn(
        'rounded-xl border-2 shadow-md transition-all overflow-hidden',
        'min-w-[240px] max-w-[300px]',
        current > 0
          ? 'border-blue-500 bg-blue-50/80 dark:bg-blue-950/30'
          : 'border-slate-400/60 bg-slate-50/90 dark:bg-slate-800/70'
      )}
    >
      <Handle type="target" position={Position.Top} className="!bg-slate-500 !w-2.5 !h-2.5" />

      {/* Header — clickable to expand/collapse */}
      <div
        className="flex items-center gap-2 px-3 py-2 cursor-pointer select-none hover:bg-slate-200/40 dark:hover:bg-slate-700/40 transition-colors"
        onClick={() => onToggle(arc)}
      >
        {isExpanded ? (
          <ChevronDown className="h-4 w-4 text-slate-500 shrink-0" />
        ) : (
          <ChevronRight className="h-4 w-4 text-slate-500 shrink-0" />
        )}
        <Layers className="h-4 w-4 text-indigo-500 shrink-0" />
        <span className="text-sm font-semibold text-foreground flex-1">{arc}</span>
        <span className="text-[10px] text-slate-400">{beatCount} 节拍</span>
      </div>

      {/* Progress bar */}
      <div className="px-3 pb-1.5">
        <div className="flex items-center gap-1.5">
          <div className="flex-1 h-1.5 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden">
            <div
              className="h-full bg-emerald-500 rounded-full transition-all"
              style={{ width: `${progress}%` }}
            />
          </div>
          <span className="text-[9px] text-slate-400">{progress}%</span>
        </div>
      </div>

      {/* Status summary pills */}
      <div className="flex flex-wrap gap-1 px-3 pb-2">
        {completed > 0 && (
          <span className="text-[9px] rounded-full bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-400 px-1.5 py-0.5">
            ✓ {completed}
          </span>
        )}
        {current > 0 && (
          <span className="text-[9px] rounded-full bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-400 px-1.5 py-0.5 animate-pulse">
            ● 当前 {current}
          </span>
        )}
        {planned > 0 && (
          <span className="text-[9px] rounded-full bg-slate-100 dark:bg-slate-700 text-slate-500 px-1.5 py-0.5">
            ○ {planned}
          </span>
        )}
        {skipped > 0 && (
          <span className="text-[9px] rounded-full bg-rose-100 dark:bg-rose-900/40 text-rose-600 px-1.5 py-0.5">
            ✗ {skipped}
          </span>
        )}
      </div>

      {/* Key characters */}
      {characters.length > 0 && (
        <div className="flex flex-wrap gap-0.5 px-3 pb-2">
          {characters.slice(0, 5).map((c) => (
            <span
              key={c}
              className="text-[9px] rounded bg-indigo-50 dark:bg-indigo-950/40 px-1 py-0.5 text-indigo-600 dark:text-indigo-400"
            >
              {c}
            </span>
          ))}
          {characters.length > 5 && (
            <span className="text-[9px] text-slate-400">+{characters.length - 5}</span>
          )}
        </div>
      )}

      <Handle type="source" position={Position.Bottom} className="!bg-slate-500 !w-2.5 !h-2.5" />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Edge styling — each edge type has a distinct visual identity
// ---------------------------------------------------------------------------

const EDGE_STYLES: Record<
  string,
  { stroke: string; dashed: boolean; label: string; animated: boolean; width: number }
> = {
  sequential: { stroke: '#94a3b8', dashed: false, label: '顺序', animated: false, width: 1.5 },
  causal: { stroke: '#f97316', dashed: false, label: '因果', animated: true, width: 2 },
  foreshadow: { stroke: '#ef4444', dashed: true, label: '伏笔', animated: true, width: 2 },
  parallel: { stroke: '#3b82f6', dashed: false, label: '并行', animated: false, width: 1.5 },
  alternative: { stroke: '#a855f7', dashed: true, label: '备选', animated: false, width: 1.5 },
  character_arc: { stroke: '#8b5cf6', dashed: true, label: '角色弧', animated: true, width: 2 },
  item_flow: { stroke: '#14b8a6', dashed: false, label: '物品流', animated: false, width: 1.5 },
};

// ---------------------------------------------------------------------------
// Layout — Progressive Disclosure with dagre
//
// Two-level layout:
// 1. Arc-level macro nodes are laid out as a vertical DAG
// 2. When an arc is expanded, its beats are laid out in a sub-cluster
//    and positioned within the arc's allocated space
// ---------------------------------------------------------------------------

function layoutProgressive(
  beats: JsonBeat[],
  edges: Array<{ from_beat: string; to_beat: string; edge_type: string }>,
  expandedArcs: Set<string>
): { positions: Map<string, { x: number; y: number }>; arcPositions: Map<string, { x: number; y: number }> } {
  const positions = new Map<string, { x: number; y: number }>();
  const arcPositions = new Map<string, { x: number; y: number }>();
  if (beats.length === 0) return { positions, arcPositions };

  // Group beats by arc
  const arcGroups = new Map<string, JsonBeat[]>();
  for (const beat of beats) {
    const arc = beat.arc ?? '未分类';
    if (!arcGroups.has(arc)) arcGroups.set(arc, []);
    arcGroups.get(arc)!.push(beat);
  }

  const arcs = [...arcGroups.keys()];

  // Build arc-level edges (edges where from and to are in different arcs)
  const arcEdges: Array<{ from: string; to: string; weight: number }> = [];
  const beatToArc = new Map<string, string>();
  for (const beat of beats) {
    beatToArc.set(beat.id, beat.arc ?? '未分类');
  }
  for (const edge of edges) {
    const fromArc = beatToArc.get(edge.from_beat);
    const toArc = beatToArc.get(edge.to_beat);
    if (fromArc && toArc && fromArc !== toArc) {
      const isMainline = edge.edge_type === 'sequential' || edge.edge_type === 'causal';
      arcEdges.push({ from: fromArc, to: toArc, weight: isMainline ? 10 : 1 });
    }
  }

  // Layout arc-level graph
  const ARC_W = 280;
  const ARC_H_COLLAPSED = 120;
  const ARC_H_EXPANDED = 400;

  const g = new dagre.graphlib.Graph();
  g.setGraph({
    rankdir: 'TB',
    nodesep: 80,
    edgesep: 40,
    ranksep: 100,
    marginx: 30,
    marginy: 30,
  });
  g.setDefaultEdgeLabel(() => ({}));

  for (const arc of arcs) {
    const isExpanded = expandedArcs.has(arc);
    g.setNode(arc, {
      width: ARC_W,
      height: isExpanded ? ARC_H_EXPANDED : ARC_H_COLLAPSED,
    });
  }

  for (const edge of arcEdges) {
    g.setEdge(edge.from, edge.to, { weight: edge.weight, minlen: 1 });
  }

  dagre.layout(g);

  for (const arc of arcs) {
    const node = g.node(arc);
    if (node) {
      arcPositions.set(arc, {
        x: node.x - ARC_W / 2,
        y: node.y - (expandedArcs.has(arc) ? ARC_H_EXPANDED : ARC_H_COLLAPSED) / 2,
      });
    }
  }

  // Layout beats within expanded arcs
  const BEAT_W = 200;
  const BEAT_H = 100;
  for (const arc of arcs) {
    if (!expandedArcs.has(arc)) continue;
    const arcBeats = arcGroups.get(arc)!;
    const arcPos = arcPositions.get(arc);
    if (!arcPos) continue;

    // Sub-layout for beats within this arc
    const subEdges = edges.filter(
      (e) => beatToArc.get(e.from_beat) === arc && beatToArc.get(e.to_beat) === arc
    );

    const subG = new dagre.graphlib.Graph();
    subG.setGraph({
      rankdir: 'TB',
      nodesep: 40,
      edgesep: 20,
      ranksep: 50,
      marginx: 10,
      marginy: 10,
    });
    subG.setDefaultEdgeLabel(() => ({}));

    for (const beat of arcBeats) {
      subG.setNode(beat.id, { width: BEAT_W, height: BEAT_H });
    }
    for (const edge of subEdges) {
      subG.setEdge(edge.from_beat, edge.to_beat, { weight: 5, minlen: 1 });
    }

    dagre.layout(subG);

    // Offset beat positions by arc position
    for (const beat of arcBeats) {
      const subNode = subG.node(beat.id);
      if (subNode) {
        positions.set(beat.id, {
          x: arcPos.x + (subNode.x - BEAT_W / 2) + 40,
          y: arcPos.y + (subNode.y - BEAT_H / 2) + 80,
        });
      }
    }
  }

  return { positions, arcPositions };
}

// ---------------------------------------------------------------------------
// Main panel
// ---------------------------------------------------------------------------

export function NovelOverviewPanel() {
  const { t } = useTranslation(['panels', 'writingPrompts']);
  const { projectId } = useProject();
  const { data: repos } = useProjectRepos(projectId);
  const rootPath = repos?.[0]?.path ?? '';

  const [stats, setStats] = useState<OverviewStats>(EMPTY_STATS);
  const [graph, setGraph] = useState<JsonGraph | null>(null);
  const [graphLoading, setGraphLoading] = useState(false);
  const [graphError, setGraphError] = useState<string | null>(null);
  const [promptNotice, setPromptNotice] = useState<string | null>(null);

  const [selectedBeatId, setSelectedBeatId] = useState<string | null>(null);
  const [beatContext, setJsonBeatContext] = useState<JsonBeatContext | null>(null);
  const [expandedArcs, setExpandedArcs] = useState<Set<string>>(new Set());

  const [statusFilter, setStatusFilter] = useState<string>('all');

  // ----- refresh stats -----
  const refreshStats = useCallback(async () => {
    if (!rootPath) {
      setStats(EMPTY_STATS);
      return;
    }
    try {
      const result = await scanWorkspace(rootPath);
      setStats(result);
    } catch {
      setStats(EMPTY_STATS);
    }
  }, [rootPath]);

  // ----- story graph file path -----
  const storyGraphPath = rootPath ? `${rootPath}/.cinyuverse/story-graph.json` : '';

  // ----- refresh graph (read from .cinyuverse/story-graph.json) -----
  const refreshGraph = useCallback(async () => {
    if (!storyGraphPath) {
      setGraph(null);
      return;
    }
    setGraphLoading(true);
    setGraphError(null);
    try {
      const content = await fileTreeApi.readFile(storyGraphPath);
      const parsed = JSON.parse(content) as JsonGraph;
      // Ensure required arrays exist and edges have required fields
      setGraph({
        beats: parsed.beats ?? [],
        edges: (parsed.edges ?? []).map((e) => ({
          from_beat: e.from_beat,
          to_beat: e.to_beat,
          edge_type: e.edge_type,
          note: e.note ?? null,
        })),
      });
    } catch {
      // File may not exist yet or be empty — show empty graph
      setGraph({ beats: [], edges: [] });
    } finally {
      setGraphLoading(false);
    }
  }, [storyGraphPath]);

  // ----- save graph (write to .cinyuverse/story-graph.json) -----
  const saveGraph = useCallback(
    async (nextGraph: JsonGraph) => {
      if (!storyGraphPath) return;
      try {
        const content = JSON.stringify(nextGraph, null, 2);
        await fileTreeApi.saveFile(storyGraphPath, content);
        setGraph(nextGraph);
      } catch (err) {
        setGraphError(err instanceof Error ? err.message : String(err));
      }
    },
    [storyGraphPath]
  );

  useEffect(() => {
    refreshStats();
    refreshGraph();
  }, [refreshStats, refreshGraph]);

  // ----- build context when selection changes (computed from local graph) -----
  useEffect(() => {
    if (!selectedBeatId || !graph) {
      setJsonBeatContext(null);
      return;
    }
    const beat = graph.beats.find((b) => b.id === selectedBeatId);
    if (!beat) {
      setJsonBeatContext(null);
      return;
    }
    const predecessorIds = new Set(
      graph.edges.filter((e) => e.to_beat === selectedBeatId).map((e) => e.from_beat)
    );
    const successorIds = new Set(
      graph.edges.filter((e) => e.from_beat === selectedBeatId).map((e) => e.to_beat)
    );
    const predecessors = graph.beats.filter((b) => predecessorIds.has(b.id));
    const successors = graph.beats.filter((b) => successorIds.has(b.id));
    setJsonBeatContext({
      beat,
      predecessors,
      successors,
      characters: beat.characters ?? [],
      related_hooks: beat.hooks ?? [],
    });
  }, [selectedBeatId, graph]);

  // ----- Progressive Disclosure: layout + nodes/edges -----
  const { positions, arcPositions } = useMemo(
    () =>
      graph
        ? layoutProgressive(graph.beats, graph.edges, expandedArcs)
        : { positions: new Map<string, { x: number; y: number }>(), arcPositions: new Map<string, { x: number; y: number }>() },
    [graph, expandedArcs]
  );

  // Arc-level data for macro nodes
  const arcData = useMemo(() => {
    if (!graph) return new Map<string, ArcNodeData>();
    const groups = new Map<string, JsonBeat[]>();
    for (const beat of graph.beats) {
      const arc = beat.arc ?? '未分类';
      if (!groups.has(arc)) groups.set(arc, []);
      groups.get(arc)!.push(beat);
    }
    const result = new Map<string, ArcNodeData>();
    for (const [arc, beats] of groups) {
      const statusCounts: Record<string, number> = {};
      const charSet = new Set<string>();
      for (const b of beats) {
        statusCounts[b.status] = (statusCounts[b.status] ?? 0) + 1;
        for (const c of b.characters ?? []) charSet.add(c);
      }
      result.set(arc, {
        arc,
        beatCount: beats.length,
        statusCounts,
        characters: [...charSet],
        isExpanded: expandedArcs.has(arc),
        onToggle: (a: string) =>
          setExpandedArcs((prev) => {
            const next = new Set(prev);
            if (next.has(a)) next.delete(a);
            else next.add(a);
            return next;
          }),
      });
    }
    return result;
  }, [graph, expandedArcs]);

  // Build the node list: arc macro nodes + beat nodes (only for expanded arcs)
  const nodes = useMemo<Node[]>(() => {
    if (!graph) return [];
    const result: Node[] = [];

    // Arc macro nodes
    for (const [arc, data] of arcData) {
      const pos = arcPositions.get(arc) ?? { x: 0, y: 0 };
      result.push({
        id: `arc:${arc}`,
        type: 'arcNode',
        position: pos,
        data: data as unknown as Record<string, unknown>,
        draggable: true,
      });
    }

    // Beat nodes — only for expanded arcs
    for (const beat of graph.beats) {
      const arc = beat.arc ?? '未分类';
      if (!expandedArcs.has(arc)) continue;
      if (statusFilter !== 'all' && beat.status !== statusFilter) continue;
      const pos = positions.get(beat.id);
      if (!pos) continue;
      result.push({
        id: beat.id,
        type: 'beatNode',
        position: pos,
        data: { beat, isSelected: beat.id === selectedBeatId } as unknown as Record<string, unknown>,
        selected: beat.id === selectedBeatId,
      });
    }

    return result;
  }, [graph, arcData, arcPositions, positions, expandedArcs, selectedBeatId, statusFilter]);

  // Build edges: cross-arc edges (always visible, between arc nodes) +
  // within-arc edges (only when arc is expanded, between beat nodes)
  const edges = useMemo<Edge[]>(() => {
    if (!graph) return [];
    const result: Edge[] = [];
    const beatToArc = new Map<string, string>();
    for (const beat of graph.beats) {
      beatToArc.set(beat.id, beat.arc ?? '未分类');
    }

    // Cross-arc edges: connect arc macro nodes
    const seenArcEdges = new Set<string>();
    for (const edge of graph.edges) {
      const fromArc = beatToArc.get(edge.from_beat);
      const toArc = beatToArc.get(edge.to_beat);
      if (!fromArc || !toArc || fromArc === toArc) continue;

      // If both arcs are expanded, draw beat-to-beat
      if (expandedArcs.has(fromArc) && expandedArcs.has(toArc)) {
        const style = EDGE_STYLES[edge.edge_type] ?? EDGE_STYLES.sequential;
        const isCrossEdge =
          edge.edge_type === 'foreshadow' ||
          edge.edge_type === 'character_arc' ||
          edge.edge_type === 'item_flow' ||
          edge.edge_type === 'alternative';
        result.push({
          id: `${edge.from_beat}->${edge.to_beat}:${edge.edge_type}`,
          source: edge.from_beat,
          target: edge.to_beat,
          label: style.label,
          type: isCrossEdge ? 'default' : 'smoothstep',
          animated: style.animated,
          style: {
            stroke: style.stroke,
            strokeWidth: style.width,
            strokeDasharray: style.dashed ? '6 4' : undefined,
          },
          labelStyle: { fill: style.stroke, fontSize: 10, fontWeight: 600 },
          labelBgStyle: { fill: 'rgba(255,255,255,0.85)' },
        });
        continue;
      }

      // Otherwise, aggregate as arc-to-arc edge
      const arcEdgeKey = `${fromArc}->${toArc}:${edge.edge_type}`;
      if (seenArcEdges.has(arcEdgeKey)) continue;
      seenArcEdges.add(arcEdgeKey);

      const style = EDGE_STYLES[edge.edge_type] ?? EDGE_STYLES.sequential;
      result.push({
        id: arcEdgeKey,
        source: `arc:${fromArc}`,
        target: `arc:${toArc}`,
        label: style.label,
        type: 'smoothstep',
        animated: style.animated,
        style: {
          stroke: style.stroke,
          strokeWidth: style.width,
          strokeDasharray: style.dashed ? '6 4' : undefined,
        },
        labelStyle: { fill: style.stroke, fontSize: 11, fontWeight: 600 },
        labelBgStyle: { fill: 'rgba(255,255,255,0.85)' },
      });
    }

    // Within-arc edges: only for expanded arcs
    for (const edge of graph.edges) {
      const fromArc = beatToArc.get(edge.from_beat);
      const toArc = beatToArc.get(edge.to_beat);
      if (!fromArc || !toArc || fromArc !== toArc) continue;
      if (!expandedArcs.has(fromArc)) continue;

      const style = EDGE_STYLES[edge.edge_type] ?? EDGE_STYLES.sequential;
      result.push({
        id: `${edge.from_beat}->${edge.to_beat}:${edge.edge_type}`,
        source: edge.from_beat,
        target: edge.to_beat,
        label: style.label,
        type: 'smoothstep',
        animated: style.animated,
        style: {
          stroke: style.stroke,
          strokeWidth: style.width,
          strokeDasharray: style.dashed ? '6 4' : undefined,
        },
        labelStyle: { fill: style.stroke, fontSize: 10, fontWeight: 600 },
        labelBgStyle: { fill: 'rgba(255,255,255,0.85)' },
      });
    }

    return result;
  }, [graph, expandedArcs]);

  const [rfNodes, setRfNodes] = useState<Node[]>(nodes);
  const [rfEdges, setRfEdges] = useState<Edge[]>(edges);

  useEffect(() => setRfNodes(nodes), [nodes]);
  useEffect(() => setRfEdges(edges), [edges]);

  const onNodesChange = useCallback(
    (changes: NodeChange[]) => setRfNodes((nds) => applyNodeChanges(changes, nds)),
    []
  );
  const onEdgesChange = useCallback(
    (changes: EdgeChange[]) => setRfEdges((eds) => applyEdgeChanges(changes, eds)),
    []
  );
  const onConnect: OnConnect = useCallback(
    (connection) => {
      const fromBeat = connection.source;
      const toBeat = connection.target;
      if (graph && fromBeat && toBeat) {
        const newEdge = { from_beat: fromBeat, to_beat: toBeat, edge_type: 'sequential', note: null };
        void saveGraph({
          beats: graph.beats,
          edges: [...graph.edges, newEdge],
        });
      }
      setRfEdges((eds) =>
        addEdge({ ...connection, type: 'smoothstep' }, eds)
      );
    },
    [graph, saveGraph]
  );

  const onNodeClick = useCallback((_: unknown, node: Node) => {
    // Arc nodes handle their own click via the toggle in data
    if (node.id.startsWith('arc:')) return;
    setSelectedBeatId(node.id);
  }, []);

  const selectedBeat = useMemo(
    () => graph?.beats.find((b) => b.id === selectedBeatId) ?? null,
    [graph, selectedBeatId]
  );

  // ----- agent session actions -----
  const { visibleRightSession } = useKanbanSessionContext();
  const setRightPanelVisible = useLayoutStore(
    (state) => state.setRightPanelVisible
  );
  const requestPrefill = useComposerPrefillStore((s) => s.requestPrefill);

  const fillPromptIntoSession = useCallback(
    (promptText: string) => {
      setPromptNotice(null);
      // Require an existing session on the right panel — do NOT create one.
      if (!visibleRightSession?.sessionId) {
        setPromptNotice(t('panels:overview.noSession'));
        setRightPanelVisible(true);
        return;
      }
      // Push the prompt into the composer via the prefill store — the
      // SessionComposerInput will consume it and replace its text.
      requestPrefill(promptText);
      setRightPanelVisible(true);
    },
    [visibleRightSession, requestPrefill, setRightPanelVisible, t]
  );

  const handleGenerateGraph = useCallback(() => {
    const tpl = getWritingPrompt('generate-story-graph');
    if (!tpl) return;
    const prompt = tpl.build({
      bookName: undefined,
      guidance: '',
    });
    void fillPromptIntoSession(prompt);
  }, [fillPromptIntoSession]);

  const handleInferBeat = useCallback(() => {
    if (!selectedBeat || !beatContext || !graph) return;
    const tpl = getWritingPrompt('infer-beat');
    if (!tpl) return;
    const fullGraphJson = JSON.stringify(graph, null, 2);
    const prompt = tpl.build({
      beatId: selectedBeat.id,
      beatTitle: selectedBeat.title,
      beatDescription: selectedBeat.description ?? '',
      fullGraph: fullGraphJson,
    });
    void fillPromptIntoSession(prompt);
  }, [selectedBeat, beatContext, graph, fillPromptIntoSession]);

  const handleWriteBeat = useCallback(() => {
    if (!selectedBeat || !beatContext || !graph) return;
    const tpl = getWritingPrompt('write-beat');
    if (!tpl) return;
    const chapterNum = selectedBeat.chapter_hint
      ? Number(selectedBeat.chapter_hint)
      : undefined;
    const fullGraphJson = JSON.stringify(graph, null, 2);
    const prompt = tpl.build({
      beatId: selectedBeat.id,
      beatTitle: selectedBeat.title,
      beatDescription: selectedBeat.description ?? '',
      chapterNumber: chapterNum,
      fullGraph: fullGraphJson,
    });
    void fillPromptIntoSession(prompt);
  }, [selectedBeat, beatContext, graph, fillPromptIntoSession]);

  // ----- status update (modify local graph, save to JSON) -----
  const updateStatus = useCallback(
    async (beatId: string, status: string) => {
      if (!graph) return;
      const nextBeats = graph.beats.map((b) =>
        b.id === beatId ? { ...b, status } : b
      );
      await saveGraph({ beats: nextBeats, edges: graph.edges });
    },
    [graph, saveGraph]
  );

  const deleteBeat = useCallback(
    async (beatId: string) => {
      if (!graph) return;
      if (!confirm(t('panels:overview.deleteConfirm'))) return;
      const nextBeats = graph.beats.filter((b) => b.id !== beatId);
      const nextEdges = graph.edges.filter(
        (e) => e.from_beat !== beatId && e.to_beat !== beatId
      );
      if (selectedBeatId === beatId) setSelectedBeatId(null);
      await saveGraph({ beats: nextBeats, edges: nextEdges });
    },
    [graph, saveGraph, selectedBeatId, t]
  );

  // ----- derived stats -----
  const beatStats = useMemo(() => {
    if (!graph) return { total: 0, completed: 0, current: 0, planned: 0 };
    const total = graph.beats.length;
    const completed = graph.beats.filter((b) => b.status === 'completed').length;
    const current = graph.beats.filter((b) => b.status === 'current').length;
    const planned = graph.beats.filter((b) => b.status === 'planned').length;
    return { total, completed, current, planned };
  }, [graph]);

  // ----- render -----
  if (!projectId) {
    return (
      <div className="overview-overlay bg-background text-foreground flex h-full w-full items-center justify-center">
        <p className="text-muted-foreground">{t('panels:overview.noProject')}</p>
      </div>
    );
  }

  return (
    <div className="overview-overlay bg-background text-foreground flex h-full w-full flex-col overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b px-4 py-2">
        <div className="flex items-center gap-2">
          <BookOpen className="h-4 w-4 text-muted-foreground" />
          <h2 className="text-sm font-semibold">{t('panels:overview.storyGraph')}</h2>
          <span className="text-xs text-muted-foreground">
            {t('panels:overview.statsBeats', beatStats)}
          </span>
        </div>
        <div className="flex items-center gap-1.5">
          <Button size="sm" variant="secondary" onClick={handleGenerateGraph} disabled={false}>
            <Wand2 className="h-3.5 w-3.5" />
            {t('panels:overview.generateStoryGraph')}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => {
              const allArcs = new Set<string>();
              for (const b of graph?.beats ?? []) allArcs.add(b.arc ?? '未分类');
              setExpandedArcs(allArcs);
            }}
            title="展开全部"
          >
            <Maximize2 className="h-3.5 w-3.5" />
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setExpandedArcs(new Set())}
            title="折叠全部"
          >
            <Minimize2 className="h-3.5 w-3.5" />
          </Button>
          <Button size="sm" variant="ghost" onClick={() => { refreshGraph(); refreshStats(); }}>
            <RefreshCw className={cn('h-3.5 w-3.5', graphLoading && 'animate-spin')} />
          </Button>
        </div>
      </div>

      {/* Prompt action notice (e.g. "no session" warning) */}
      {promptNotice && (
        <div className="flex items-center justify-between gap-2 border-b bg-amber-50 dark:bg-amber-950/30 px-4 py-1.5 text-xs text-amber-700 dark:text-amber-400">
          <span>{promptNotice}</span>
          <button
            className="text-amber-500 hover:text-amber-700"
            onClick={() => setPromptNotice(null)}
          >
            ×
          </button>
        </div>
      )}

      {/* Stats strip */}
      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 border-b px-4 py-1.5 text-xs text-muted-foreground">
        <span>{t('panels:overview.chapterCount')}: {stats.chapterCount}</span>
        <span>{t('panels:overview.totalWords')}: {stats.totalWords.toLocaleString()}</span>
        <span>{t('panels:overview.characterCount')}: {stats.characterCount}</span>
        <span>
          {t('panels:overview.hooks')}: {stats.hookTotal}
          {stats.hookTotal > 0 && (
            <span className="ml-1">
              ({t('panels:overview.hookResolution', {
                resolved: stats.hookResolved,
                open: stats.hookOpen,
                rate: stats.hookTotal > 0 ? Math.round((stats.hookResolved / stats.hookTotal) * 100) : 0,
              })})
            </span>
          )}
        </span>
      </div>

      {/* Filter bar */}
      <div className="flex items-center gap-1.5 border-b px-4 py-1.5">
        {['all', 'planned', 'current', 'completed', 'skipped'].map((s) => (
          <Button
            key={s}
            size="sm"
            variant={statusFilter === s ? 'secondary' : 'ghost'}
            onClick={() => setStatusFilter(s)}
            className="h-6 px-2 text-xs"
          >
            {t(`panels:overview.filter${s.charAt(0).toUpperCase() + s.slice(1)}`)}
          </Button>
        ))}
      </div>

      {/* Main content: graph + side panel */}
      <div className="flex flex-1 overflow-hidden">
        <div className="relative flex-1">
          {graphLoading && (
            <div className="absolute inset-0 z-10 flex items-center justify-center bg-background/60">
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
              <span className="ml-2 text-sm text-muted-foreground">
                {t('panels:overview.graphLoading')}
              </span>
            </div>
          )}
          {graphError && (
            <div className="absolute inset-0 z-10 flex items-center justify-center">
              <p className="text-sm text-rose-500">{t('panels:overview.graphError')}: {graphError}</p>
            </div>
          )}
          {!graphLoading && graph && graph.beats.length === 0 && (
            <div className="absolute inset-0 z-10 flex flex-col items-center justify-center gap-3">
              <p className="text-sm text-muted-foreground">{t('panels:overview.graphEmpty')}</p>
              <Button size="sm" variant="secondary" onClick={handleGenerateGraph} disabled={false}>
                <Wand2 className="h-3.5 w-3.5" />
                {t('panels:overview.generateStoryGraph')}
              </Button>
            </div>
          )}
          {graph && graph.beats.length > 0 && (
            <ReactFlow
              nodes={rfNodes}
              edges={rfEdges}
              nodeTypes={nodeTypes}
              onNodesChange={onNodesChange}
              onEdgesChange={onEdgesChange}
              onConnect={onConnect}
              onNodeClick={onNodeClick}
              fitView
              fitViewOptions={{ padding: 0.2 }}
              proOptions={{ hideAttribution: true }}
            >
              <Background variant={BackgroundVariant.Dots} gap={20} size={1} />
              <Controls showInteractive={false} />
              <MiniMap
                pannable
                zoomable
                nodeColor={(n) => {
                  if (n.id.startsWith('arc:')) return '#6366f1';
                  const beat = (n.data as unknown as BeatNodeData)?.beat;
                  if (!beat) return '#94a3b8';
                  switch (beat.status) {
                    case 'completed': return '#10b981';
                    case 'current': return '#3b82f6';
                    case 'skipped': return '#f43f5e';
                    case 'revised': return '#f59e0b';
                    default: return '#94a3b8';
                  }
                }}
              />
            </ReactFlow>
          )}
        </div>

        {/* Side panel: beat details + agent actions */}
        {selectedBeat && (
          <div className="w-72 border-l overflow-y-auto p-3 space-y-3">
            <div>
              <div className="text-[10px] uppercase tracking-wide text-muted-foreground">
                {BEAT_TYPE_LABELS[selectedBeat.beat_type] ?? selectedBeat.beat_type}
              </div>
              <h3 className="text-sm font-semibold leading-snug">{selectedBeat.title}</h3>
              <div className="mt-1 text-xs text-muted-foreground">
                {t('panels:overview.beatStatus')}: {selectedBeat.status}
              </div>
            </div>

            {selectedBeat.description && (
              <p className="text-xs text-muted-foreground leading-relaxed">
                {selectedBeat.description}
              </p>
            )}

            {selectedBeat.chapter_hint != null && (
              <div className="text-xs">
                <span className="text-muted-foreground">{t('panels:overview.beatChapter')}: </span>
                <span>第 {Number(selectedBeat.chapter_hint)} 章</span>
              </div>
            )}

            {beatContext ? (
              <div className="space-y-2 text-xs">
                {beatContext.predecessors.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatPredecessors')}
                    </div>
                    <ul className="list-disc pl-4 space-y-0.5">
                      {beatContext.predecessors.map((p) => (
                        <li key={p.id} className="cursor-pointer hover:text-blue-500"
                          onClick={() => setSelectedBeatId(p.id)}>
                          {p.title}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {beatContext.successors.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatSuccessors')}
                    </div>
                    <ul className="list-disc pl-4 space-y-0.5">
                      {beatContext.successors.map((s) => (
                        <li key={s.id} className="cursor-pointer hover:text-blue-500"
                          onClick={() => setSelectedBeatId(s.id)}>
                          {s.title}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {beatContext.characters.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatCharacters')}
                    </div>
                    <div className="flex flex-wrap gap-1">
                      {beatContext.characters.map((c) => (
                        <span key={c} className="rounded bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5">
                          {c}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {beatContext.related_hooks.length > 0 && (
                  <div>
                    <div className="text-muted-foreground mb-0.5">
                      {t('panels:overview.beatHooks')}
                    </div>
                    <div className="flex flex-wrap gap-1">
                      {beatContext.related_hooks.map((h) => (
                        <span key={h} className="rounded bg-rose-50 dark:bg-rose-950/40 px-1.5 py-0.5 text-rose-600">
                          {h}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ) : null}

            {/* Agent actions — primary */}
            <div className="flex flex-col gap-1.5 pt-2 border-t">
              <Button size="sm" variant="secondary" onClick={handleInferBeat} disabled={!beatContext}>
                <Sparkles className="h-3.5 w-3.5" /> {t('panels:overview.inferBeat')}
              </Button>
              <Button size="sm" variant="secondary" onClick={handleWriteBeat} disabled={!beatContext}>
                <PenLine className="h-3.5 w-3.5" /> {t('panels:overview.writeBeat')}
              </Button>
            </div>

            {/* Quick status actions */}
            <div className="flex flex-col gap-1.5 pt-2 border-t">
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'current')}>
                <CircleDot className="h-3.5 w-3.5" /> {t('panels:overview.markCurrent')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'completed')}>
                <CheckCircle2 className="h-3.5 w-3.5" /> {t('panels:overview.markCompleted')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => updateStatus(selectedBeat.id, 'planned')}>
                <Circle className="h-3.5 w-3.5" /> {t('panels:overview.markPlanned')}
              </Button>
              <Button size="sm" variant="ghost" onClick={() => deleteBeat(selectedBeat.id)}>
                <Trash2 className="h-3.5 w-3.5" /> {t('panels:overview.deleteBeat')}
              </Button>
            </div>
          </div>
        )}

        {/* Inline conversation session slot — adopts the shared right panel host */}
        <OverviewSessionSlot visible={true} />
      </div>
    </div>
  );
}
