import type { EditorSchemeColors } from '@/features/theme/config/editorSchemes'
import { ICLS_EXTENDED_KEY_MAP } from '@/features/theme/config/iclsKeyMapExtended'

/** IDEA .icls 颜色键 → CinyuVerse 编辑器配色字段 */
export const ICLS_COLOR_KEY_MAP: Record<string, keyof EditorSchemeColors> = {
  TEXT: 'text',
  FOREGROUND: 'text',
  DEFAULT_FOREGROUND: 'text',
  BACKGROUND: 'background',
  EDITOR_BACKGROUND: 'background',
  GUTTER_BACKGROUND: 'background',
  CONSOLE_BACKGROUND: 'background',
  CARET_COLOR: 'cursor',
  CARET_ROW_COLOR: 'activeLine',
  SELECTION_BACKGROUND: 'selection',
  SELECTED_TEXT_BACKGROUND: 'selection',
  LINE_NUMBERS_COLOR: 'lineNumber',
  WHITESPACES_COLOR: 'lineNumber',
  HYPERLINK_COLOR: 'link',
  KEYWORD: 'bold',
  CLASS_NAME: 'heading',
  FUNCTION_DECLARATION: 'heading',
  FUNCTION_CALL: 'link',
  METHOD_CALL: 'link',
  STRING: 'quote',
  NUMBER: 'code',
  DEFAULT_NUMBER: 'code',
  COMMENT: 'comment',
  LINE_COMMENT: 'comment',
  BLOCK_COMMENT: 'comment',
  DOC_COMMENT: 'comment',
  METADATA: 'italic',
  ANNOTATION: 'italic',
  MARKUP_TAG: 'bold',
  MARKUP_ATTRIBUTE: 'italic',
  MARKUP_HEADING: 'heading',
  MARKUP_LINK: 'link',
  MARKUP_CODE: 'code',
  MARKDOWN_TEXT: 'text',
  MARKDOWN_BOLD: 'bold',
  MARKDOWN_ITALIC: 'italic',
  MARKDOWN_LINK: 'link',
  MARKDOWN_BLOCK_QUOTE: 'quote',
  MARKDOWN_CODE: 'code',
  MARKDOWN_CODE_SPAN: 'code',
  MARKDOWN_HEADER_LEVEL_1: 'heading',
  MARKDOWN_HEADER_LEVEL_2: 'heading',
  MARKDOWN_HEADER_LEVEL_3: 'heading',
  MARKDOWN_HEADER_LEVEL_4: 'heading',
  MARKDOWN_HEADER_LEVEL_5: 'heading',
  MARKDOWN_HEADER_LEVEL_6: 'heading',
  HTML_TAG: 'bold',
  HTML_COMMENT: 'comment',
  XML_TAG: 'bold',
  JSON_KEY: 'bold',
  JSON_STRING: 'quote',
  CUSTOM_KEYWORD1: 'bold',
  CUSTOM_STRING: 'quote',
  CUSTOM_NUMBER: 'code',
  CUSTOM_LINE_COMMENT: 'comment',
  CUSTOM_BLOCK_COMMENT: 'comment',
  VALID_STRING_ESCAPE: 'code',
  INVALID_STRING_ESCAPE: 'code',
  ...ICLS_EXTENDED_KEY_MAP,
}

export const ICLS_ATTRIBUTE_KEY_MAP: Record<string, keyof EditorSchemeColors> = {
  ...ICLS_COLOR_KEY_MAP,
  HYPERLINK: 'link',
  FOLLOWED_HYPERLINK: 'link',
  CONSOLE_NORMAL_OUTPUT: 'text',
  CONSOLE_ERROR_OUTPUT: 'bold',
  CONSOLE_USER_INPUT: 'quote',
  DIFF_INSERTED: 'quote',
  DIFF_DELETED: 'bold',
  DIFF_MODIFIED: 'heading',
}

export const ICLS_FIELD_PRIORITY: Record<keyof EditorSchemeColors, string[]> = {
  background: ['BACKGROUND', 'EDITOR_BACKGROUND', 'GUTTER_BACKGROUND'],
  text: ['TEXT', 'FOREGROUND', 'MARKDOWN_TEXT'],
  heading: ['MARKDOWN_HEADER_LEVEL_1', 'MARKUP_HEADING', 'CLASS_NAME'],
  bold: ['KEYWORD', 'MARKDOWN_BOLD', 'MARKUP_TAG'],
  italic: ['METADATA', 'MARKDOWN_ITALIC', 'ANNOTATION'],
  link: ['HYPERLINK_COLOR', 'MARKDOWN_LINK', 'MARKUP_LINK'],
  quote: ['STRING', 'MARKDOWN_BLOCK_QUOTE', 'MARKUP_QUOTE'],
  code: ['NUMBER', 'MARKDOWN_CODE', 'MARKUP_CODE'],
  comment: ['COMMENT', 'DOC_COMMENT', 'LINE_COMMENT'],
  cursor: ['CARET_COLOR'],
  selection: ['SELECTION_BACKGROUND'],
  activeLine: ['CARET_ROW_COLOR'],
  lineNumber: ['LINE_NUMBERS_COLOR'],
}
