export { default as AppShellLayout } from './AppShellLayout.vue'
export { default as LayoutHeader } from './LayoutHeader.vue'
export { default as LayoutSidebar } from './LayoutSidebar.vue'
export type { SidebarMenuItem } from './LayoutSidebar.vue'
export { default as PageLayout } from './PageLayout.vue'
export { default as WorkspaceBreadcrumb } from './WorkspaceBreadcrumb.vue'
export type { WorkspaceBreadcrumbTrailItem } from './WorkspaceBreadcrumb.vue'
export type { WorkspaceNavItem } from '@/config/workspace-nav'
export { WORKSPACE_NAV_ITEMS } from '@/config/workspace-nav'
